### PR TITLE
token expired callback

### PR DESCRIPTION
**Pull request by priore**
I created a callback in the case of an expired token, with the token decoding itself

```javascript
router.use(
    jwt({secret: 'ssshhhh', isExpired: (err, req, next) => {
        // check conditions
        if (req.user.uid == null) {
            return next(err);
        }

        // TODO: ...
        return next();
    }}),
    (req, res, next) => {
      // TODO: ...
});
```

### CODE REVIEW

**Comment by george-norris-salesforce** [comment]
Can this be merged? @jfromaniello

**Comment by FieryCod** [comment]
@jfromaniello ?

**Comment by justin-scx** [comment]
This functionality would be useful to me.

**Comment by shawkinsl** [comment]
Wow, this is exactly what I needed when I wrote #209; I think I'll just checkout & deploy this to my own npm package instead 8)

**Comment by shawkinsl** [comment]
For posterity, and anyone else using this implementation: while writing tests for this, I found that invalid issuer errors can be swallowed under certain circumstances. This will hopefully be resolved in https://github.com/priore/express-jwt/pull/1 .

**Comment by jfromaniello** [comment]
I added this feature in express-jwt@8.2.0

https://github.com/auth0/express-jwt#handling-expired-tokens

**Pull request closed without merging**
