### PR TITLE
update jsonwebtoken to 8.1.0

### PR DESCRIPTION
**Pull request by ilyapx**

### CODE REVIEW

**Comment by ilyapx** [comment]
new version of jsonwebtoken remove the nextTick on each callback, this should help abit with the performance

**Comment by angela-mylo** [comment]
update on this dependency also addresses some vulnerabilities.
+1

**Comment by nmors** [comment]
Please merge this, see https://nodesecurity.io/advisories/566

**Comment by jfrazx** [comment]
Looks like this was handled with 11f3ac4. Now it needs 8.3.0

**Pull request closed without merging**
