### PR TITLE
Custom Token

### PR DESCRIPTION
**Pull request by kivervinicius**
I needed a different standard token, so I created a customTokenHeader option if it is passed obligatorily is necessary to call the getToken function. README was updated

### CODE REVIEW

**Comment by jfromaniello** [comment]
I don't understand why you need this. Currently if you provide a `getToken` function, the `authorization` header is not read?

Can you explain a little bit more what you need!

Thanks and sorry for the delay

**Comment by kivervinicius** [comment]
Hello, by default you must use the authorization token, and in my application I needed it to be another name for convenience to what we have already developed. As the idea is to be something that has a certain freedom, I had the idea to implement it. Thank you

**Comment by kivervinicius** [comment]
can you analysis this?

**Comment by kivervinicius** [comment]
:(

**Pull request closed without merging**
