### PR TITLE
bump jsonwebtoken version to 7

### PR DESCRIPTION
**Pull request by timelf123**
https://github.com/auth0/express-jwt/issues/124

### CODE REVIEW

**Comment by timelf123** [comment]
ping @jfromaniello

**Comment by lahdekorpi** [comment]
ping?

**Comment by davebaol** [comment]
jsonwebtoken 7.3.0 is out and this project is still using 6.2.0, which at the present time is 75 commits behind the master. :flushed: 

C'mon, can someone at auth0 merge this PR? :pray:

**Comment by ruyadorno** [comment]
cc @ggoodman do you happen to know anyone that could help us out?

**Comment by gillesdemey** [comment]
This would fix https://github.com/auth0/express-jwt/issues/148 when it lands

**Comment by jfromaniello** [comment]
Thank you and sorry for the delay, I have published this change on `v5.3.0`

**Pull request merged**
